services:
  bloglist-frontend:
    image: bloglist-frontend
    build:
      context: ./bloglist-frontend
    container_name: bloglist-frontend

  bloglist-backend:
    image: bloglist-backend
    build:
      context: ./bloglist-backend
    container_name: bloglist-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - bloglist-frontend
      - bloglist-backend
