services:
  bloglist-frontend:
    image: bloglist-frontend-dev
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    container_name: bloglist-frontend-dev

  bloglist-backend:
    image: bloglist-backend-dev
    build:
      context: ./bloglist-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-backend:/usr/src/app
    container_name: bloglist-backend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - bloglist-frontend
      - bloglist-backend
