name: Deployment Pipeline

on:
  push:
    branches:
      - part11-exercises

  pull_request:
    branches: [part11-exercises]
    types: [opened, synchronize]

env:
  SHOULD_DEPLOY_AND_TAG: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm run install:all

      - name: Lint
        run: npm run lint:all

      - name: Build
        run: npm run build:ui

      - name: Add test MongoDB URI to .env files
        run: |
          echo "SECRET=${{ secrets.SECRET }}" >> bloglist-backend/.env
          echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> bloglist-backend/.env
          echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> bloglist-e2e/.env

      - name: Install Playwright browsers
        run: cd bloglist-e2e && npx playwright install --with-deps

      - name: Test E2E
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4.4.3
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploy
        if: ${{ env.SHOULD_DEPLOY_AND_TAG == 'true' }}
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        if: ${{ env.SHOULD_DEPLOY_AND_TAG == 'true' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
